//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonareISS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cerere
    {
        public int Id_Cerere { get; set; }
        public string Celula_Ceruta { get; set; }
    
        public virtual Medic Medic { get; set; }
        public virtual OperatorCentru OperatorCentru { get; set; }
        public virtual Pacient Pacient { get; set; }
    }
}
