//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonareISS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChestionarDonare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChestionarDonare()
        {
            this.Boli = new HashSet<Boli>();
        }
    
        public int Id_ChestionarDonare { get; set; }
        public Nullable<int> Greutate { get; set; }
        [Display(Name= "Interventii chirurgicale")]
        public string InterventiiChirurgicale { get; set; }
        public Nullable<int> Puls { get; set; }
        public string Tensiune { get; set; }
        public string Destinatar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boli> Boli { get; set; }
        public virtual Donator Donator { get; set; }
    }
}
