//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonareISS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISSEntities : DbContext
    {
        public ISSEntities()
            : base("name=ISSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boli> Boli { get; set; }
        public virtual DbSet<Cerere> Cerere { get; set; }
        public virtual DbSet<ChestionarDonare> ChestionarDonare { get; set; }
        public virtual DbSet<Donator> Donator { get; set; }
        public virtual DbSet<GlobuleRosii> GlobuleRosii { get; set; }
        public virtual DbSet<Medic> Medic { get; set; }
        public virtual DbSet<OperatorCentru> OperatorCentru { get; set; }
        public virtual DbSet<Pacient> Pacient { get; set; }
        public virtual DbSet<Plasma> Plasma { get; set; }
        public virtual DbSet<ProbaDeSange> ProbaDeSange { get; set; }
        public virtual DbSet<PungaDeSange> PungaDeSange { get; set; }
        public virtual DbSet<Stoc> Stoc { get; set; }
        public virtual DbSet<Trombocite> Trombocite { get; set; }
        public virtual DbSet<Utilizator> Utilizator { get; set; }
    }
}
