//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonareISS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PungaDeSange
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PungaDeSange()
        {
            this.ProbaDeSange = new HashSet<ProbaDeSange>();
        }
    
        public int Id_Punga { get; set; }
    
        public virtual GlobuleRosii GlobuleRosii { get; set; }
        public virtual Plasma Plasma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProbaDeSange> ProbaDeSange { get; set; }
        public virtual Trombocite Trombocite { get; set; }
    }
}
