//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonareISS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trombocite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trombocite()
        {
            this.PungaDeSange = new HashSet<PungaDeSange>();
        }
    
        public int Id_Trombocite { get; set; }
        public Nullable<int> Cantitate { get; set; }
        public Nullable<System.DateTime> DataRecoltarii { get; set; }
        public Nullable<System.DateTime> DataExpirarii { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PungaDeSange> PungaDeSange { get; set; }
    }
}
